<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\BLite.Bson\BLite.Bson.csproj" />
    <ProjectReference Include="..\..\src\BLite.Core\BLite.Core.csproj" />
    <ProjectReference Include="..\..\src\BLite.SourceGenerators\BLite.SourceGenerators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>
